In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
%matplotlib inline

In [14]:
vector = torch.tensor([3,3,2], dtype = None, device='cuda', requires_grad=False)
vector.type(torch.float32)

tensor([3., 3., 2.], device='cuda:0')

## Finding the max, mean, min, etc of Tensors

In [16]:
x = torch.arange(0,11, 1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# get max and min
x.max(), x.min(), torch.max(x), torch.min(x)

(tensor(10), tensor(0), tensor(10), tensor(0))

In [24]:
# .mean() method can only take in float or complex dtype, so we have to convert it
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32)), x.sum(), torch.sum(x) 

(tensor(5.), tensor(5.), tensor(55), tensor(55))

In [26]:
# Get index at which the max/ min occurs at
x.argmin(), x.argmax(), torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(10), tensor(0), tensor(10))

## Reshaping, viewing, stacking, squeezing, and unsqueezing tensors

In [32]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [40]:
# Reshape the dimensions. Would work with any combination as long as the size stays the same
x_reshaped = x.reshape(1,10)
x_reshaped = x.reshape(10,1)
# x_reshaped = x.reshape(5,2)
# x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [42]:
# Change the view
z = x.view(2,5)
z, z.shape

# Changing z changes x (because a view of a tensor shares the same memeory as the original tensor)
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [47]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [58]:
# Removes all single dimensions from a tensor
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[ 5.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 5.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]),
 torch.Size([10]))

In [65]:
# unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dim
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New target: tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [70]:
# Permute - returns a view with elements rearranged
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour_channels] -> image data

# Permute the original tensor to rearrange the axis (or dim) order, i.e. (height, width, colour_channels) -> (colour_channels, height, width)
# !! Permuted tensors shares same memory with original tensors 
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## PyTorch Tensors & NumPy
* Data in NumPy, want in PyTorch tensor
* PyTorch tensor -> NumpPy

In [75]:
# !! Numpy default is float64, but pytorch tensor default is float32
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32)

In [76]:
# Changing value in array doesn't change in tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [77]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, tensor.dtype, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

In [78]:
# Changing value in tensor doesn't change in array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [79]:
# For reproducibility, set seed
RANDOM_NUMBER = 42
torch.manual_seed(RANDOM_NUMBER)

## Best practice to setup device agnostic code

e.g. run on GPU if available, otherwise run on CPU

In [83]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

# Count number of devices
torch.cuda.device_count()

1

In [97]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [98]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [99]:
tensor[0] = 6
# Changing tensor doesn't affect tensor_on_gpu, they do not share the same memory
tensor, tensor_on_gpu

(tensor([6, 2, 3]), tensor([1, 2, 3], device='cuda:0'))

In [101]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)